SIH2020/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from buyer import views as bv
from django.conf import settings
from django.conf.urls.static import static

from home import views as hv
urlpatterns = [
    path('admin/', admin.site.urls),
    path('buyer/',include(('buyer.urls','buyer'),namespace='buyer')),
    path('seller/',include('seller.urls')),
    path('',include('home.urls')),
    path('logout/',hv.user_logout,name='logout'),
    # path('logistic/',include('logistic.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('aboutus/',views.about,name='about'),
    path('checkprice/',views.checkprice,name='check'),
]


#AIzaSyCQvKXOnYbsExXlMe-TnudIwupJeejmE8o

seller/urls.py
from django.urls import path
from . import views

app_name="seller"

urlpatterns = [
    path('signup/',views.register,name='sellersignup'),
    path('login/',views.user_login,name='sellerlogin'),
    path('sell/',views.sell,name='sell'),
    path('dashboard/',views.dashboard,name='dashboard')
]

seller/models.py
from django.db import models
from django.contrib.auth.models import User
from uuid import uuid4
from django.utils.crypto import get_random_string

def generateUUID():
    return str(uuid4())
# Create your models here.

class SellerProfile(models.Model):
    sid=models.CharField(max_length=10, blank=True,  default='S'+get_random_string(8).upper())
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    phone=models.CharField(max_length=10)
    district=models.CharField(max_length=20)
    state=models.CharField(max_length=20)
    aadhar=models.CharField(max_length=12)
    is_buyer=models.BooleanField(default=False)
    is_seller=models.BooleanField(default=True)

    def __str__(self):
        return self.user.username

seller/forms.py
from django import forms
from .models import SellerProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class UserForm(UserCreationForm):
    email=forms.EmailField()
    class meta:
        model=User
        fields=['email','password1','password2']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.EmailInput(attrs={ 'placeholder': 'Email Address '})
        self.fields['password1'].widget = forms.PasswordInput(attrs={ 'placeholder': 'Enter Password '})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'placeholder': 'Password confirmation'})
        self.fields.pop('username')

class SellerSignupForm(forms.ModelForm):
    class Meta:
        model=SellerProfile
        fields=['first_name','last_name','phone','district','aadhar','state']

    def __init__(self, *args, **kwargs):
        super(SellerSignupForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget=forms.TextInput(attrs={'id':'firstname','placeholder':'First Name','required':'required'})
        self.fields['last_name'].widget=forms.TextInput(attrs={'id':'lastname','placeholder':'Last Name','required':'required'})
        self.fields['phone'].widget=forms.TextInput(attrs={'id':'contact','placeholder':'Contact No.','required':'required'})
        self.fields['district'].widget=forms.TextInput(attrs={'id':'district','placeholder':'District','required':'required'})
        self.fields['aadhar'].widget=forms.TextInput(attrs={'id':'aadhar','placeholder':'Aadhar','required':'required'})
        self.fields['state'].widget=forms.TextInput(attrs={'id':'state','placeholder':'State','required':'required'})

seller/views.py
from django.shortcuts import render,redirect
from .forms import UserForm,SellerSignupForm
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
import requests
import json
from django.conf import settings
from buyer.models import BuyerProfile
from django.contrib.auth.decorators import login_required
# Create your views here.

url = "https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001ccc5a88319d2459f7a6636ac3d094690&format=json&offset=0&limit=10000"
l=0


def price(loc):
    r = requests.request("GET", url)
    data=r.json()
    l={}
    f=9
    for i in range(int(data['count'])):
        if data['records'][i]['state']==loc:
                l[str(i)]=data['records'][i]
                f=1

    return([l,data['updated_date']])

@login_required
def dashboard(request):
    return render(request,'seller/seller_dashboard.html')

@login_required
def sell(request):
    state=None
    district=None
    commodity=None
    seller=None
    d=None
    s=None
    if request.method=='POST':
        commodity=request.POST.get('commodity')
        district=request.POST.get('district')
        state=request.POST.get('state')


        if district==None:
            district=BuyerProfile.objects.filter(state=state,commodity=commodity).values_list('district',flat=True)
        else:
            d='true'
            seller=BuyerProfile.objects.filter(state=state,commodity=commodity,district=district)


    print(commodity,state,district)
    return render(request,'seller/sell.html',{'commodity':commodity,'state':state,'districts':district,'sellers':seller,'d':d,'s':s})



def register(request):
    if request.method=="POST":
        form=UserForm(data=request.POST)
        sform=SellerSignupForm(data=request.POST)
        if form.is_valid() and sform.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            data = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            result = r.json()
            print(result['success'])
            if result['success']:
                user=form.save(commit=False)
                user.username=form.cleaned_data['email']
                user.save()
                profile=sform.save(commit=False)
                profile.state=request.POST.get('state')
                profile.district=request.POST.get('district')
                profile.user=user
                profile.save()
                messages.success(request,'Your account has been created !')
                return redirect('home')

        else:
            print(form.errors)
            print(sform.errors)
            messages.error(request,'Invalid Input. Kindly Fill again !')
            return redirect('home')

    else:
        form=UserForm()
        sform=SellerSignupForm()

    return render(request,'seller/seller_signup.html',{'form':form,'sform':sform})


def user_login(request):
    if request.method=='POST':
        email=request.POST.get('email')
        password=request.POST.get('password')
        print(email,password)
        user = authenticate(username=email, password=password)
        if user:
            if user.is_active and user.sellerprofile.is_seller:
                login(request, user)
                messages.success(request, f'You are logged in successfully!')
                return redirect('seller:dashboard')

        else:
            messages.error(request,'Please Check your username and password !')
    return render(request,'seller/seller_login.html')

seller/templates/seller/seller_dashboard.html
{% extends 'home/home.html' %}
{% load static %}

{% block content %}

<div id="content">

    <span class="slide">
        <a href="#" onclick="openSlideMenu()">
            <i class="fas fa-bars"></i>
        </a>
    </span>

    <div id="menu" class="nav">
        <a href="#" class="close" onclick="closeSlideMenu()">
            <i class="fas fa-times"></i>
        </a>
        <a href="#">
            Dashboard&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a>
        <a href="{% url 'seller:sell' %}" onclick="sell_click()">Sell
            Commodity&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a>
        <a
            href="#">Complete&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a>
        <a
            href="#">InProgress&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</a>
    </div>

    <section class="menu-section" id="dashboard">

    </section>

    <section class="menu-section" id="complete">

    </section>

    <section class="menu-section" id="inprogress">

    </section>

    <div class="container">
        <div class="row">
            <div class="col-lg-3 text-center">
                <div class="card">
                    <div class="card-header">
                        Space
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        </blockquote>
                    </div>
                </div>
            </div>
            <div class="col-lg-1 text-center"></div>
            <div class="col-lg-3 text-center">
                <div class="card">
                    <div class="card-header">
                        Space
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        </blockquote>
                    </div>
                </div>
            </div>
            <div class="col-lg-1"></div>
            <div class="col-lg-3 text-center">
                <div class="card">
                    <div class="card-header">
                        Space
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        </blockquote>
                    </div>
                </div>
            </div>
            <div class="col-lg-1"></div>
        </div>
        <div class="row mt-5">
                <div class="col-lg-3 text-center">
                    <div class="card">
                        <div class="card-header">
                            Space
                        </div>
                        <div class="card-body">
                            <blockquote class="blockquote mb-0">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                            </blockquote>
                        </div>
                    </div>
                </div>
                <div class="col-lg-1 text-center"></div>
                <div class="col-lg-3 text-center">
                    <div class="card">
                        <div class="card-header">
                            Space
                        </div>
                        <div class="card-body">
                            <blockquote class="blockquote mb-0">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                            </blockquote>
                        </div>
                    </div>
                </div>
                <div class="col-lg-1"></div>
                <div class="col-lg-3 text-center">
                    <div class="card">
                        <div class="card-header">
                            Space
                        </div>
                        <div class="card-body">
                            <blockquote class="blockquote mb-0">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                            </blockquote>
                        </div>
                    </div>
                </div>
                <div class="col-lg-1"></div>
            </div>
    </div>



</div>

<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
<script>
    function openSlideMenu() {
        document.getElementById('menu').style.width = '250px';
        document.getElementById('content').style.marginLeft = '250px';
    }
    function closeSlideMenu() {
        document.getElementById('menu').style.width = '0';
        document.getElementById('content').style.marginLeft = '0';
    }
    function next() {
        document.getElementById('second-div').style.display = "block"
    }
    function sell_click() {
        document.getElementById("sell").style.display = "block"
    }
</script>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

{% endblock content %}

seller/templates/seller/seller_login.html
{% extends 'home/home.html' %}
{% load static %}
{% block content %}
<img src="https://c.pxhere.com/photos/c2/f4/agriculture_beautiful_view_city_park_cloud_clouds_countryside_crop_daylight-1563595.jpg!d" style="width:100% ; height:66.7%">
<style>
    @font-face {
        font-family: 'Typold Book';
        font-style: normal;
        font-weight: normal;
        src: local('Typold Book'), url('..\\fonts\\Typold\\The Northern Block Ltd - Typold Book.woff') format('woff');
    }
</style>


<div id="love" class="container text-center mt-1" style="position : absolute ; top :7% ; left:5%">
    <h1 style="margin-top: 10%;font-family: 'Typold Book'">LOGIN</h1>

    <form method="POST">
        {% csrf_token %}

        <input type="text" id="username" placeholder="Email" name="email" required><br><br>
        <input type="password" id="password" placeholder="Password" name="password" required><br><br>

        <button type="submit" class="btn btn-primary">LOGIN</button>
    </form>
    <div class="mt-2">New User ?? <a href="{% url 'seller:sellersignup' %}" id="open_signup">Sign Up</a></div>

</div>
{% endblock content %}

seller/templates/seller/seller_signup.html
{% extends 'home/home.html' %}
{% load static %}
{% block content %}
<script src="{% static 'buyer/js/cities.js' %}"></script>
<img src="https://static.wixstatic.com/media/ab4e4f_ab97fbadb4bf4faea2121b8c00884433~mv2.jpg"
    style="width:100% ; height:85%">
<!-- <img src="" style="width:100% ; height:81%"> -->
<a name="buyer" class="login">
    <div id="singnup" class="container text-center mt-5" style="position: absolute ; left:7% ; top:13%">
        <h1>SIGN UP</h1>
        <form method="POST" class="mb-0">
            <div class="row">
                <div class="col-lg-6 text-right">
                    {% csrf_token %}
                    <!-- <label for="firstname">First Name</label><br> -->
                    {{sform.first_name}}<br><br>

                    <!-- <label for="contact">Contact No.</label><br> -->
                    {{sform.phone}}<br><br>
                    <!-- <label for="district">State</label><br> -->
                    <select name="state" style="position: relative ; left:353px ; width:184px"
                        onchange="print_city('state', this.selectedIndex);" id="sts" name="stt" class="form-control"
                        required></select><br><label>
                        <script language="javascript">print_state("sts");</script>
                        <!-- <label for="password" style="margin-top: -2%;">Enter a Password</label><br> -->
                        {{form.password1}}<br>
                </div>
                <div class="col-lg-6 text-left">
                    <!-- <label for="lastname">Last Name</label><br> -->
                    {{sform.last_name}}<br><br>
                    <!-- <label for="email">Email</label><br> -->
                    {{form.email}}<br><br>
                    <!-- <label for="district" style="margin-top: -2%;">District</label> -->
                    <select id="state" style="width:184px" class="form-control" name="district" required>
                    </select><br>

                    <!-- <label for="again password">ReEnter Password</label><br> -->
                    {{form.password2}}<br><br><label>
                </div>
            </div>
            <!-- <label for="aadhar">Aadhar No.</label><br> -->
            {{sform.aadhar}}<br>
            <div class="alert alert-danger" id="alert" role="alert" style="display: none ; width:auto">
                Passwords Did'nt Match ....Try Again
            </div>
            <script src='https://www.google.com/recaptcha/api.js'></script>
            <div class="g-recaptcha" style="margin-left: 36% ; margin-top:2%"
                data-sitekey="6Ldjrc4UAAAAAPIfnXkHkPKpJwOV3yxkOXagmQwM">
            </div>

            <button type="submit" class="btn btn-primary mt-4" id="signup-button">Sign Up</button>
        </form>

        <div class="mt-2">Already Have Account.. <a href="{% url 'seller:sellerlogin' %}" id="open_login">Login</a>
        </div>

    </div>
</a>
{% endblock content %}

seller/templates/seller/test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form method="POST">
      {% csrf_token %}
        <div class="row pt-4 pb-4">

            {% if commodity %}
            <select name="warehouse-type" required>
                <option value="{{commodity}}">{{commodity}}</option>
            </select>
            {% else %}
            <div class="col-lg-6 text-center">

              <label for="commodity">Commodity:</label><br>
              <select id="commodity" name='commodity'>
                  <option>-------Select Commodity-------</option>
                  <option>Fruits</option>
                  <option>Vegetables</option>
                  <option>Medicinal</option>
                  <option>Dairy</option>
                  <option>Grains</option>
                  <option>BioFuel</option>
                  <option value="crop">Crops</option>
                  <option>Plants</option>
                  <option>None</option>
              </select><br><br>

            </div>
            {% endif %}

            {% if state %}
            <div class="col-lg-6 text-center">
                    <label for="region">Where You Want To Sell</label><br>

                        <select class="" name="state">
                          <option value="{{state}}">{{state}}</option>
                        </select>

                        <select class="" name="district">
                            {% for district in districts %}
                              <option value="{{district}}">{{district}}</option>
                            {% endfor %}
                        </select>
                        <button class="btn btn-success ml-5" type="submit">Next</button>
                    {% else %}

                          <select name=state>
                          <option value="">------------Select State------------</option>
                          <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
                          <option value="Andhra Pradesh">Andhra Pradesh</option>
                          <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                          <option value="Assam">Assam</option>
                          <option value="Bihar">Bihar</option>
                          <option value="Chandigarh">Chandigarh</option>
                          <option value="Chhattisgarh">Chhattisgarh</option>
                          <option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
                          <option value="Daman and Diu">Daman and Diu</option>
                          <option value="Delhi">Delhi</option>
                          <option value="Goa">Goa</option>
                          <option value="Gujarat">Gujarat</option>
                          <option value="Haryana">Haryana</option>
                          <option value="Himachal Pradesh">Himachal Pradesh</option>
                          <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                          <option value="Jharkhand">Jharkhand</option>
                          <option value="Karnataka">Karnataka</option>
                          <option value="Kerala">Kerala</option>
                          <option value="Lakshadweep">Lakshadweep</option>
                          <option value="Madhya Pradesh">Madhya Pradesh</option>
                          <option value="Maharashtra">Maharashtra</option>
                          <option value="Manipur">Manipur</option>
                          <option value="Meghalaya">Meghalaya</option>
                          <option value="Mizoram">Mizoram</option>
                          <option value="Nagaland">Nagaland</option>
                          <option value="Orissa">Orissa</option>
                          <option value="Pondicherry">Pondicherry</option>
                          <option value="Punjab">Punjab</option>
                          <option value="Rajasthan">Rajasthan</option>
                          <option value="Sikkim">Sikkim</option>
                          <option value="Tamil Nadu">Tamil Nadu</option>
                          <option value="Tripura">Tripura</option>
                          <option value="Uttaranchal">Uttaranchal</option>
                          <option value="Uttar Pradesh">Uttar Pradesh</option>
                          <option value="West Bengal">West Bengal</option>
                          </select>
                          <button class="btn btn-success ml-5" type="submit" >Next</button>
                      {% endif %}<br><br>


                </form>
  </body>
</html>