SIH2020/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from buyer import views as bv
from django.conf import settings
from django.conf.urls.static import static

from home import views as hv
urlpatterns = [
    path('admin/', admin.site.urls),
    path('buyer/',include(('buyer.urls','buyer'),namespace='buyer')),
    path('seller/',include('seller.urls')),
    path('',include('home.urls')),
    path('logout/',hv.user_logout,name='logout'),
    # path('logistic/',include('logistic.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

buyer/urls.py
from django.urls import path
from . import views

app_name='buyer'

urlpatterns = [
    path('signup/',views.register,name='buyersignup'),
    path('login/',views.user_login,name='buyerlogin'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('aboutus/',views.about,name='about'),
    path('checkprice/',views.checkprice,name='check'),
]


#AIzaSyCQvKXOnYbsExXlMe-TnudIwupJeejmE8o

seller/urls.py
from django.urls import path
from . import views

app_name="seller"

urlpatterns = [
    path('signup/',views.register,name='sellersignup'),
    path('login/',views.user_login,name='sellerlogin'),
    path('sell/',views.sell,name='sell'),
    path('dashboard/',views.dashboard,name='dashboard')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
import requests
# Create your views here.

def home(request):
    print('heom')
    return render(request,'home/hero.html')

def about(request):
    return render(request,'home/about-us.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect('home')


url = "https://api.data.gov.in/resource/9ef84268-d588-465a-a308-a864a43d0070?api-key=579b464db66ec23bdd000001ccc5a88319d2459f7a6636ac3d094690&format=json&offset=0&limit=10000"

def price(loc):
    r = requests.request("GET", url)
    data=r.json()
    l={}
    f=9
    for i in range(int(data['count'])):
        if data['records'][i]['state']==loc:
                l[str(i)]=data['records'][i]
                f=1

    return([l,data['updated_date']])

@login_required
def checkprice(request):
    if request.method=="POST":
        loc=request.POST.get('state')
        l=price(loc)
        print(loc)
        return render(request,'home/result.html',{'price':l[0],'date':l[1]})
    else:
        return render(request,'home/checkprice.html')

home/templates/home/about-us.html
{% extends 'home/home.html' %}

{% load static %}

{% block content %}
<style>
    @font-face {
        font-family: ikaros-sans;
        src: url("../../home/fonts/Ikaros\ sans/@font-face");
        font-weight: normal;
    }
</style>
<section>

    <section class="mt-5">
        <div class="container text-center mb-5">
            <h1>Reducing Waste by Digitizing the Network of <br>Farmers, Logistics and Warehouses</h1>
            <p class="mt-5" style="font-size:1.5em; font-family:ikaros-sans;">
                Wth growing population the world is facing scarcity of food. When farmer sells his crop to warehouses,
                most of the food gets wasted during transportation.
                Moreover, Since as far back as one can remember, information and commodity flow in rural India have been
                dominated
                by players who have thrived on the opaqueness, inconsistency and fragmentation of the ecosystem.
                Technology, while making rapid strides in the everyday life of an urban dweller, has had little to no
                impact on the rural economy.<br><br>
                At Ann Suraksha, we believe that with millions of rural internet users coming online for the
                first time on mobile, it is time they reap its benefits. We are building this future with our fully
                integrated and tech enabled supply chain that enables farmers PAN India to save their crops from
                wastage, earn more by selling their
                produce directly to businesses and have comfort of selling from their home.<br><br>
                We’re building a future where farmers are businessmen, and not just growers. We want you to be a part of
                it.
            </p>
        </div>
    </section>


    {% endblock content %}

home/templates/home/checkprice.html
{% extends 'home/home.html' %}
{% load static %}
{% block content %}
  <section>
    <img src="https://cdn.britannica.com/s:700x500/17/196817-050-6A15DAC3/vegetables.jpg" style="background-size: cover ; width:100%;">
    <h1 class="text-center" style="position: relative ; margin-top:-43%; color:white;">REALTIME MANDI PRICE</h1>
    <div class="container">
      <!-- <h1 class="text-center" style="color: white;">REALTIME MANDI PRICE</h1>-->
      <form method="POST" style="text-align: center;">
        {% csrf_token %}
        <h1 style="color: #23f3fa">State </h1>
        <table >
          <tr>
            <td style="color: white;"></td>
            <td ><select name="state" style="text-align: center;">
                <option value="">------------Select State------------</option>
                <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
                <option value="Andhra Pradesh">Andhra Pradesh</option>
                <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                <option value="Assam">Assam</option>
                <option value="Bihar">Bihar</option>
                <option value="Chandigarh">Chandigarh</option>
                <option value="Chhattisgarh">Chhattisgarh</option>
                <option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
                <option value="Daman and Diu">Daman and Diu</option>
                <option value="Delhi">Delhi</option>
                <option value="Goa">Goa</option>
                <option value="Gujarat">Gujarat</option>
                <option value="Haryana">Haryana</option>
                <option value="Himachal Pradesh">Himachal Pradesh</option>
                <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                <option value="Jharkhand">Jharkhand</option>
                <option value="Karnataka">Karnataka</option>
                <option value="Kerala">Kerala</option>
                <option value="Lakshadweep">Lakshadweep</option>
                <option value="Madhya Pradesh">Madhya Pradesh</option>
                <option value="Maharashtra">Maharashtra</option>
                <option value="Manipur">Manipur</option>
                <option value="Meghalaya">Meghalaya</option>
                <option value="Mizoram">Mizoram</option>
                <option value="Nagaland">Nagaland</option>
                <option value="Orissa">Orissa</option>
                <option value="Pondicherry">Pondicherry</option>
                <option value="Punjab">Punjab</option>
                <option value="Rajasthan">Rajasthan</option>
                <option value="Sikkim">Sikkim</option>
                <option value="Tamil Nadu">Tamil Nadu</option>
                <option value="Tripura">Tripura</option>
                <option value="Uttaranchal">Uttaranchal</option>
                <option value="Uttar Pradesh">Uttar Pradesh</option>
                <option value="West Bengal">West Bengal</option>
              </select></td><br>
          </tr>

        </table>
        <br>
        <button type="submit" class="btn btn-primary">Check</button>
      </form>
    </div>
  </section>

{% endblock content %}

home/templates/home/hero.html
{% extends 'home/home.html' %}
{% load static %}

{% block content %}

<section id="hero-section">
    <style>
        @font-face {
            font-family: ikaros-sans;
            src: url("../../home/fonts/Ikaros\ sans/@font-face");
            font-weight: normal;
        }
    </style>

    <section id="hero-section">
        <div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'home/images/top-3.jpg' %}" class="d-block w-100">
                </div>
                <div class="carousel-item">
                    <img src="{%static 'home/images/top-1.jpg' %}" class="d-block w-100" />
                </div>
                <div class="carousel-item ">
                    <img src="{% static 'home/images/top-2.jpg' %}"
                        class="d-block w-100" />
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </section>
    <section id="highlights">
        <div class="row text-center justify-content-center pt-5 pb-5" style="width:101.2% ; background-color: #f7f7f7;">
            <div class="ml-4 mr-4 col-lg-2 col-md-2 col-sm-2 col-xs-2 col-md-2 col-sm-2 col-xs-2 events-card">
                <div class="row">
                    <div class="card text-black rounded-circle">
                        <br>
                        <img src="{% static 'home/images/region-logo.png' %}"
                            style="height:20% ; width:25% ; position: relative ; left:37%">
                        <h2 class="card-title text-success">Regions<br>Covered</h2>
                        <p class="card-text" style="font-size:2em">40+</p>
                    </div>
                </div>
            </div>
            <div class="ml-4 mr-4 col-lg-2 col-md-2 col-sm-2 col-xs-2 col-md-2 col-sm-2 col-xs-2 events-card">
                <div class="row">
                    <div class="card text-black rounded-circle">
                        <br>
                        <img src="{% static 'home/images/farm-logo.png' %}"
                            style="height:20% ; width:25% ; position: relative ; left:37%">
                        <h2 class="card-title text-success">Farmers Connected</h2>
                        <p class="card-text" style="font-size:2em">1000+</p>
                    </div>
                </div>
            </div>

            <div class="ml-4 mr-4 col-lg-2 col-md-2 col-sm-2 col-xs-2 col-md-2 col-sm-2 col-xs-2 events-card">
                <div class="row">
                    <div class="card text-black rounded-circle">
                        <br>
                        <img src="{% static 'home/images/warehouse-logo.png' %}"
                            style="height:20% ; width:25% ; position: relative ; left:37%">
                        <h2 class="card-title text-success">Happy Customers</h2>
                        <p class="card-text" style="font-size:2em">1000+</p>
                    </div>
                </div>
            </div>
            <div class="ml-4 mr-4 col-lg-2 col-md-2 col-sm-2 col-xs-2 col-md-2 col-sm-2 col-xs-2 events-card">
                <div class="row">
                    <div class="card text-black rounded-circle">
                        <br>
                        <img src="{% static 'home/images/logistics-logo.png' %}"
                            style="height:20% ; width:25% ; position: relative ; left:37%">
                        <h2 class="card-title text-success">Logistics Connected</h2>
                        <p class="card-text" style="font-size:2em">50+</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <button class="btn rounded-pill bg-success" onclick="chat()" id="chat-button"
    style="position: fixed ; right:22px ; bottom:22px ;z-index: 1;">Chat</button>
    <div style="display: none" id="chat-iframe" style="position: absolute ; right:22px ; bottom:22px">
    <iframe height="430" width="350" allow="microphone;" src="https://console.dialogflow.com/api-client/demo/embedded/annSuraksha" style="position:fixed ; right:22px ; bottom:22px ; z-index: 500"></iframe>
    </div>

    <section id="abouts-us">
        <div class="grid mt-5 container mb-5" style="height: 24em;">
            <div class="card mb-10" style="height:100% ">
                <div class="row no-gutters" style="height: 100%">
                    <div class="col-md-6">
                        <img src="{% static 'home/images/top-image1.jpg' %}" class="card-img"
                            style="height: 100% ; width:100%;" />
                    </div>
                    <div class="col-md-6 text-center">
                        <div class="card-body" style="font-family: ikaros-sans; font-size: 1.2em;"><br>
                            <h1 class="card-title">About Us</h1>
                            <p class="card-text">
                                Since as far back as one can remember, information and commodity flow in rural India
                                have
                                been dominated
                                by players who have thrived on the opaqueness, inconsistency and fragmentation of the
                                ecosystem.
                                Technology, while making rapid strides in the everyday life of an urban dweller.....
                            </p>
                            <a href="about-us.html"><button class="btn btn-primary" type="button">Read
                                    More</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="women">
        <div class="grid mt-5 container mb-5" style="height: 28em;">
            <div class="card mb-10" style="height:100% ">
                <div class="row no-gutters" style="height: 100%">
                    <div class="col-md-6 text-center">
                        <div class="card-body" style="font-family: ikaros-sans; font-size: 1.2em;">
                            <h1 class="card-title">Schemes for Women</h1>
                            <p class="card-text">
                                <ul class="text-left">
                                    <li><a href="http://mksp.gov.in/">Mahila kisan Sashaktikaran Pariyojana Insurance</a></li>
                                    <li><a href="http://vikaspedia.in/agriculture/women-and-agriculture/special-provisions-for-women-farmers-in-national-schemes#section-5">Mission for Integrated Development of Horticulture (MIDH)</a></li>
                                    <li><a
                                            href="http://vikaspedia.in/agriculture/women-and-agriculture/special-provisions-for-women-farmers-in-national-schemes#section-6">National
                                            Mission on Oilseeds & Oil Palm (NMOOP)</a></li>
                                    <li><a
                                            href="http://vikaspedia.in/agriculture/women-and-agriculture/special-provisions-for-women-farmers-in-national-schemes#section-7">Integrated
                                            Scheme for Agricultural Marketing (ISAM)</a></li>
                                    <li><a
                                            href="http://vikaspedia.in/agriculture/women-and-agriculture/special-provisions-for-women-farmers-in-national-schemes#section-8">National
                                            Food Security Mission (NFSM)</a></li>
                                    <li><a
                                            href="http://vikaspedia.in/agriculture/women-and-agriculture/special-provisions-for-women-farmers-in-national-schemes#section-9">National
                                            Mission for Sustainable Agriculture (NMSA)</a></li>
                                    <li><a
                                            href="http://vikaspedia.in/agriculture/women-and-agriculture/special-provisions-for-women-farmers-in-national-schemes#section-10">Sub-Mission
                                            on Agricultural Mechanization (SMAM)</a></li>
                                    <li><a
                                            href="http://vikaspedia.in/agriculture/women-and-agriculture/special-provisions-for-women-farmers-in-national-schemes#section-3">Agri-Clinics
                                            & Agri-Business Centers (ACABC)</a></li>
                                    <li><a
                                            href="http://vikaspedia.in/agriculture/women-and-agriculture/special-provisions-for-women-farmers-in-national-schemes#section-3">Agriculture
                                            Technology Management Agency (ATMA)</a></li>
                                    <li><a class="women-text"
                                            href="http://vikaspedia.in/agriculture/women-and-agriculture/special-provisions-for-women-farmers-in-national-schemes#section-3">Mass
                                            Media Support to Agricultural Extension</a></li>
                                </ul>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="{% static 'home/images/women.jpg' %}" class="card-img"
                            style="height: 100% ; width:100%;" />
                    </div>
                </div>
            </div>
    </section>

    <section id="testimonials" class="pb-5 text-center" style="background-color: #f7f7f7">
        <h1 class="pt-2 pb-2">Highlights</h1>
        <div class="container-fluid w-50 text-center h-70">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'home/images/highlights2.jpg' %}" style="height:300px ; width:100%">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'home/images/highlights.jpg' %}" style="height:300px ; width:100%">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'home/images/Highlights1.jpg' %}" style="height:300px ; width:100%">
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </section>
    {% endblock content %}

home/templates/home/home.html
{% load static %}

<html>

<head>
    <title>Ann Suraksha</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link href="{% static 'home/css/main.css' %}" type="text/css" rel="stylesheet" />
    <link href="{% static 'home/css/seller_dashboard.css' %}" type="text/css" rel="stylesheet" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css"
        integrity="sha384-REHJTs1r2ErKBuJB0fCK99gCYsVjwxHrSU0N7I1zl9vZbggVJXRMsv/sLlOAGb4M" crossorigin="anonymous" />

</head>

<body>
    <div class="navbar" style="background-color: #e8dbda">
        <div class="container-fluid">
            <div class="logo">
                <img src="{% static 'home/images/logo.png' %}" style="height:50px ; width:50px">
                <h1 style="float:right">&nbspAnn Suraksha</h1>
            </div>
            <div class="toggle" style="background-color: #00BCD4;">
                <span style="background-color: white;"></span>
                <span style="background-color: white;"></span>
                <span style="background-color: white;"></span>
                <span style="background-color: white;"></span>
            </div>
            <div class="links">
                <ul>
                    <li style="display:inline-block ; padding:15px ; font-size:1.3em">
                        <img src="{% static 'home/images/home-icon.png' %}" style="height: 25px ; width:25px">
                        <a href="{% url 'home' %}">&nbspHome</a>
                    </li>
                    <li style="display:inline-block ; padding:15px ; font-size:1.3em">
                        <img src="{% static 'home/images/farmer-icon.png' %}" style="height: 25px ; width:25px;">
                        <a href="{% url 'seller:sellerlogin' %}">Seller</a>
                    </li>
                    <li style="display:inline-block ; padding:15px ; font-size:1.3em">
                        <img src="{% static 'home/images/warehouse-icon.png' %}" style="height: 25px ; width:25px;">
                        <a href="{% url 'buyer:buyerlogin' %}">&nbspBuyer</a>
                    </li>
                    <li style="display:inline-block ; padding:15px ; font-size:1.3em">
                        <img src="{% static 'home/images/logistics-icon.png' %}" style="height: 25px ; width:25px">
                        <a href="../../../logistics/templates/logistics/logistics_login.html">&nbspLogistics</a>
                    </li>

                    <!--<li style="display:inline-block ; padding:15px ; font-size:1.3em">
                        <img src="{% static 'home/images/scheme-icon.png' %}" style="height: 25px ; width:25px">
                        <a href="http://agricoop.nic.in/programmes-schemes-listing" target="_blank">&nbspSchemes</a>
                    </li>-->
                    <li style="display:inline-block ; padding:15px ; font-size:1.3em">
                        <img src="{% static 'home/images/aboutus-icon.png' %}" style="height: 25px ; width:25px">
                        <a href="{% url 'about' %}">&nbspAbout Us</a>
                    </li>
                    <li class="nav-item dropdown" style="display:inline-block ; padding:15px ; font-size:1.3em">
                        <!-- <img src="{% static 'home/images/scheme-icon.png' %}" style="height: 25px ; width:25px"> -->
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Utility
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'check' %}">Check-Mandi-Price</a>
                            <a class="dropdown-item" href="http://agricoop.nic.in/programmes-schemes-listing"
                                target="_blank">Schemes</a>
                            <a class="dropdown-item" href="../home/checkprice.html">Weather</a>
                            <a class="dropdown-item" href="../home/checkprice.html">Price-Prediction</a>
                            {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            {% endif %}

                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">{{message}}</div>
    {% endfor %}

    {% endif %}
    {% block content %} {% endblock %}

    <section id="footer" style="background-color: #08080a ; color:white">
        <div class="container-fluid">
            <div class="row" style="width:99%">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                    <h4><span style="position: relative ; left:16%">Ann</span><br><span
                            style="position: relative ; left:4%">Suraksha</span></h4>
                    <img src="{% static 'home/images/logo.png' %}"
                        style="height: 50px ; width:50px ; position: relative ; left:15%">
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
                    <nav class="nav flex-column">
                        <a class="nav-link" href="../../seller/templates/seller_login.html"
                            style="color:white">Farmers</a>
                        <a class="nav-link" href="#" style="color:white">Buyer</a>
                        <a class="nav-link" href="../../logistics/templates/logistics/logistics_login.html"
                            style="color:white">Logistics</a>
                    </nav>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 text-right">
                    <h4>Kisan Helpline:</h4>
                    <a href="tel:18001801551" style="color:white">1800-180-1551</a><br>
                    <a href="http://agriculture.gov.in/" target="_blank"
                        style="color: blue !important;">http://agriculture.gov.in/</a>
                </div>
            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

    <script type="text/javascript">
        function chat() {
            document.getElementById('chat-button').style.display = "none"
            document.getElementById('chat-iframe').style.display = "block"
        }
    </script>
</body>

<script type="text/javascript"></script>
</body>

</html>

home/templates/home/result.html
{% extends 'home/home.html' %}
{% load static %}
{% block content %}
  <section>
    <img src="http://www.fullhdwpp.com/wp-content/uploads/Single-Crop_www.FullHDWpp.com_.jpg" style="background-size: cover ; width:100%">
    <h3 style="position: relative ; margin-top:-43%" class="container mb-4">Last Updated ON : {{ date }}</h3>
    <div class="w3-responsive container">
      <table class="w3-table-all" border=3 style="color: white;font-size: 25" width="1200">
        <th>State</th>
        <th>District</th>
        <th>Market</th>
        <th>Commodity</th>
        <th>Min Price</th>
        <th>Max Price</th>
        <b>
          <th class="w3-center">Modal Price</th>
        </b>
        {% for key,value in price.items %}
        <tr>
          <td>{{value.state}}</td>
          <td>{{value.district}}</td>
          <td>{{value.market}}</td>
          <td>{{value.commodity}}</td>
          <td>{{value.min_price}}</td>
          <td>{{value.max_price}}</td>
          <td>{{value.modal_price}}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </section>
  <br><br><br><br><br><br><br>

  {% endblock content %}